---
title: Portfolio | Lok Sang Ho
author: Lok Sang Ho
email: loksangho@icloud.com
description: Welcome to my portfolio. Here you will find my work as a 3D artist. Enjoy!
baseurl: "/"
url: http://www.loksangho.com
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
